version: "3.9"
services:
    db:
        build: sampledb
        volumes:
            - run:/run
            - data:/data
        environment:
            POSTGRES_PASSWORD: insecure
            PGDATA: /data
            PGHOST: /run/postgresql
        ports:
            - "5432"
        healthcheck:
            test: ["CMD", "psql", "-U", "postgres", "-d", "pagila", "-c", "select count(*) from actor"]
            interval: 1s
            timeout: 1s
            retries: 1
            start_period: 1s
        cap_add:
            - NET_ADMIN
    pgwire:
        build: pgwire
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - ./src:/src
            - run:/run
            - ./tmp:/tmp
        environment:
            POSTGRES_PASSWORD: insecure
            PGHOST: /run/postgresql
        cap_add:
            - NET_ADMIN
        command: tc qdisc add dev eth0 root netem delay 100ms; /usr/bin/make
volumes:
    data:
    run:
# vim: expandtab
